### PR TITLE
implemented privacy icon

### PR DESCRIPTION
**Pull request by Jemiiah**
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature

Resolves: #878

## Release Notes

- **New Features**
	- Introduced `EyeIconSlashed` for an alternative visual representation of the eye icon.
	- Added a new hook, `useHidePortfolio`, allowing users to toggle the visibility of their portfolio balance.
	- Updated `ProfileCard` and `ChartEntry` components to conditionally display masked balance values based on the visibility state.

- **Bug Fixes**
	- Enhanced code consistency with trailing commas in type definitions.

These updates improve user experience by providing additional visual options and better control over portfolio visibility.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Please set the cursor to pointer for the show/hide button so that when we hover it we know it's clickable

**Comment by GradleD** [comment]
<div onClick={() => setHidePortfolio(!hidePortfolio)} className={`${styles.pointer}`}>
    {hidePortfolio ? <EyeIconSlashed /> : <EyeIcon />}
</div>

**Comment by Jemiiah** [comment]
@Marchand-Nicolas working on the changes

**Review by GradleD — APPROVED** [review]

**Review by fricoben — APPROVED** [review]
lgtm

**Pull request merged**
